 # schema.yml

 version: 2

 sources:
   - name: raw
     schema: gz_raw_data
     tables:
       - name: sales
         identifier: raw_gz_sales
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: Id for each distinct order and primary key to ship table
             tests:
               - unique
               - not_null
           - name: products_id
             description: If for each disctinct products and primary key to products table
             tests:
               - unique
               - not_null
           - name: revenue
             description: ammount of turnover
           - name: quantity
             description: number of products
       - name: product
         identifier: stg_raw__product
         description: table to descript price for each products
         columns:
           - name: products_id
             description: Id for each products and foreign key to sales
             tests:
               - unique
               - not_null
           - name: purchase_price
             description: price to each distinct products
               
       - name: ship
         identifier: stg_raw__ship
         description: table to descript cost for shipping
         columns:
           - name: orders_id
             description: id for each orders Foreign key to sales table
             tests:
               - unique
               - not_null
           - name: shipping_fee
             description: fees for shipping
           - name: log_cost
             description: logistics cost
           - name: ship_cost
             description: shipping cost