 # schema.yml

 version: 2

 sources:
  - name: raw
    schema: gz_raw_data
    description: Raw data files de GreenWizz
    tables:
      - name: sales 
        identifier: raw_gz_sales
        description: Tables des ventes de GreenWizz
        columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: Id for each distinct order and primary key to ship table
           - name: pdt_id
             description: If for each disctinct product and primary key to product table  
           - name: revenue
             description: ammount of turnover
           - name: quantity
             description: number of products

        tests:
               - unique:
                  column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: Table des produits de GreenWizz
        columns:
           - name: products_id
             description: Id for each product and foreign key to sales
             tests:
               - unique
               - not_null
           - name: purchase_price
             description: price to each distinct product
              
      - name: ship
        identifier : raw_gz_ship
        description: Table des envoie de GreenWizz
        columns:
           - name: orders_id
             description: id for each orders Foreign key to dales table
             tests:
              - unique
              - not_null 
           - name: shipping_fee
             description: fees for shipping
           - name: log_cost
             description: logistics cost
           - name: ship_cost
             description: shipping cost